version: '2'
# Creates New Accounts In ./keystore
# First Create ./password.txt Containing Your Secret Passphrase
# Create Accounts with: docker-compose -f addToKeystore.yml up --scale accounts=<desired number of accounts>
# Optional: Fund the accounts in ./files/genesis.json
#           Unlock the accounts by Adding then in .env UNLOCKED_ACCOUNTS

services:
  accounts:
    build: 
      context: ${composeDir}
    volumes: # Volume in the Password File
      - ${composeDir}/password.txt:/password.txt
      - ${composeDir}/keystore/:/root/.ethereum/keystore
    entrypoint: geth account new  --password /password.txt
  